apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site-deployment
spec:
  selector:
    matchLabels:
      app: static-site
  replicas: 3 
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: static-site
        image: serfer94/task-11
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: static-site