#-*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
  config.vm.box = "generic/debian10"
  config.vm.synced_folder  ".", "/vagrant/"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081
  
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     #vm.gui = true
     vb.memory = "1024"
     vb.cpus = 2
   end

   
  config.vm.define "vm1" do |vm1|
     #vm1.vm.network "private_network", ip: "192.168.0.110"
   
    vm1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.become = true
    end
  end
end  