image_name = "serfer94/task-11"
replicas_count = "3"
container_name = "static-site"
app_name = "static-site"
service_name = "static-site-service"
deployment_name = "static-site-deployment"
node_port = "31000"