  - name: nexus
    hosts: localhost
    become: true
    pre_tasks:


    - name: Add new repo
      apt_repository:
        repo: deb http://security.debian.org/debian-security stretch/updates main
       #state: present
        update_cache: true  
        
    - name: required pckgs install
      apt:
       pkg:
        - openjdk-8-jdk
        - software-properties-common
        - build-essential
        - rsync
       state: latest

  
 
    vars:
          nexus_timezone: 'Europe/Minsk'
          nexus_admin_password: 'admin'
          nexus_public_hostname: 'nexus.vm'
          httpd_setup_enable: false
          httpd_ssl_certificate_file: "{{ vault_httpd_ssl_certificate_file }}"
          httpd_ssl_certificate_key_file: "{{ vault_httpd_ssl_certificate_key_file }}"
          nexus_anonymous_access: true
    
          nexus_repos_raw_hosted:
            - name: word-cloud-build
              version_policy: release
              write_policy: allow  # one of "allow", "allow_once" or "deny"
              strict_content_validation: false
    
          nexus_privileges:
            - name: all-repos-read
              description: 'Read & Browse access to all repos'
              repository: '*'
              actions:
                - read
                - browse
        
            - name: company-project-deploy
              description: 'Deployments to company-project'
              repository: company-project
              actions:
                - add
                - edit
            
          nexus_roles:
            - id: Developers
              name: developers
              description: All developers
              privileges:
                - nx-repository-view-*-*-*
                - nx-search-read
                - all-repos-read
                - company-project-deploy
                  
          nexus_local_users:
            - username: uploader 
              first_name: test
              last_name: task
              email: test@company.com
              password: "uploader"
              roles:
                - Developers

            - username: downloader
              first_name: test1
              last_name: task
              email: test@company.com
              password: "downloader"
              roles:
                - Developers 
            
          nexus_config_maven: false
        
          nexus_config_go: false
        
          nexus_config_raw: true 
       
    roles:
      - nexus3-oss