Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
  
  config.vm.provider "virtualbox" do |vm|
    vm.memory = "384"
    vm.cpus = 1
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.synced_folder ".", "/home/vagrant"

  config.vm.provision "shell", path: "provision.sh"
end