- name: Install plugins for jenkins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: admin
    url: http://localhost:8080
    with_dependencies: yes
  with_items:
    - locale
    - github
    - golang
    - nexus-artifact-uploader
    - timestamper 
    - pipeline
    - pipeline-stage-view
    - pipeline-github-lib
    - pipeline-build-step
    - workflow-basic-steps
    - build-pipeline-plugin
    - workflow-aggregator
    - github-branch-source
    - workflow-cps
    - ssh
    - ssh-build-agents
    - workflow-aggregator
    - workflow-durable-task-step
    - pipeline-utility-steps
    - ssh-steps
    - pipeline-stage-step
    - docker-workflow
    - docker-plugin
  register: plugin_result
  until: plugin_result is success
  retries: 5
  delay: 5
  
#- name: restart Jenkins after plugins install
#  #become: yes
#  service:
#    name: jenkins
#    state: restarted

#- name: Check that a page returns a status 200 and fail if the word "Authentication required" is not in the page contents
#  uri:
#    url: http://localhost:8080
#    return_content: yes
#    timeout: 10
#  register: this
#  retries: 60
#  delay: 5
#  failed_when: " 'Authentication required' not in this.content" 