  #- name: Copy multiple files to multiple directories
  #  copy: src={{ item.0 }} dest={{ item.1 }}
  #  with_together:
  #     - [ '/vagrant/roles/jenkins/files/jobs/goxbuild/' ]
  #     - [ '/var/lib/jenkins/jobs/goxbuild/' ]
  
  - name: Create a jenkins job
    community.general.jenkins_job:
      config: "{{ lookup('file', 'files/jobs/goxbuild/config.xml') }}"
      name: goxbuild
      password: admin
      url: http://localhost:8080
      user: admin

  # - name: Create a jenkins build 
  #   community.general.jenkins_build:
  #     name: "goxbuild"
  #     build_number: 1
  #     state: present
  #     user: admin
  #     password: admin
  #     url: http://localhost:8080