- name: Install plugins for jenkins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    timeout: 300
    url_username: admin
    url_password: admin
    url: http://localhost:8080
    with_dependencies: yes
  # with_items:
  #  - Pipeline
  #  - golang
  #  - git
  #  - github  
  #  - SSH
  #  - GitHub Branch Source  
  #  - SSH Build Agents  
  #  - nexus-artifact-uploader
  register: plugin_result
  until: plugin_result is success
  retries: 5
  delay: 10
  loop: 
    - Pipeline
    - golang
    - git
    - github  
    - SSH
    - GitHub Branch Source  
    - SSH Build Agents  
    - nexus-artifact-uploader
    - timestamper 

#- name: restart Jenkins after plugins install
#  #become: yes
#  service:
#    name: jenkins
#    state: restarted

#- name: Check that a page returns a status 200 and fail if the word "Authentication required" is not in the page contents
#  uri:
#    url: http://localhost:8080
#    return_content: yes
#    timeout: 10
#  register: this
#  retries: 60
#  delay: 5
#  failed_when: " 'Authentication required' not in this.content" 