  - name: task-06
    hosts: all
    tasks:

  - hosts: staging.vm production.vm
    become: yes
    tasks:

    - name: Creating a systemd service
      copy:
        dest: "/etc/systemd/system/wordcloud.service"
        content: |
            [Unit]
            Description=Word Cloud Generator
            
            [Service]
            WorkingDirectory=/opt/wordcloud
            ExecStart=/opt/wordcloud/word-cloud-generator
            Restart=always
            
            [Install]
            WantedBy=multi-user.target

    - name: Just force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reexec: yes

    - name: change ownership of a directory
      ansible.builtin.file:
        path: /opt/wordcloud/
        state: directory
        owner: vagrant
        group: vagrant

    - name: Download and unarchive
      copy:
        src: /vagrant/roles/jenkins/files/word-cloud-generator
        dest: /opt/wordcloud/   

    - name: Enable and start service word-cloud-generator
      ansible.builtin.systemd:
          name: wordcloud
          state: started
          enabled: yes
    

  - hosts: staging.vm
    become: yes
    tasks:
    - name: required pckgs install
      apt:
        pkg:
        - jq
        state: latest    

  
  - hosts: nexus.vm
    become: yes
    pre_tasks:

    - name: required pckgs install
      apt:
       pkg:
        - software-properties-common
       state: latest
       
    - name: Add new repo
      apt_repository:
        repo: deb http://security.debian.org/debian-security stretch/updates main
       #state: present
        update_cache: true   

    - name: openjdk-8-jdk install
      apt:
       pkg:
        - openjdk-8-jdk
       state: latest

    vars:
        nexus_timezone: 'Europe/Minsk'
        nexus_admin_password: 'admin'
        nexus_public_hostname: 'nexus.vm'
        httpd_setup_enable: false
        httpd_ssl_certificate_file: "{{ vault_httpd_ssl_certificate_file }}"
        httpd_ssl_certificate_key_file: "{{ vault_httpd_ssl_certificate_key_file }}"
        nexus_anonymous_access: true
  
        nexus_repos_raw_hosted:
          - name: word-cloud-build
            version_policy: release
            write_policy: allow  # one of "allow", "allow_once" or "deny"
            strict_content_validation: false
  
        nexus_privileges:
          - name: all-repos-read
            description: 'Read & Browse access to all repos'
            repository: '*'
            actions:
              - read
              - browse
      
          - name: company-project-deploy
            description: 'Deployments to company-project'
            repository: company-project
            actions:
              - add
              - edit
          
        nexus_roles:
          - id: Developers
            name: developers
            description: All developers
            privileges:
              - nx-repository-view-*-*-*
              - nx-search-read
              - all-repos-read
              - company-project-deploy
                
        nexus_local_users:
          - username: Uploader 
            first_name: test
            last_name: task
            email: test@company.com
            password: "admin"
            roles:
              - Developers
          
        nexus_config_maven: false
      
        nexus_config_go: false
      
        nexus_config_raw: true 
       
    roles:
      - geerlingguy.java
      - ansible-thoteam.nexus3-oss

  - hosts: jenkins.vm
    become: yes
    roles:
      - jenkins