---
version: '3.3'
services:
  nexus:
    build:
      context: .
      dockerfile: Dockerfile.Nexus
    ports: 
    - 81:8081
    network_mode: host
    image: nexus
    container_name: nexus

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    image: jenkins
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - workspace:/var/lib/jenkins/workspace/
    ports: 
    - 80:8080
    network_mode: host
    container_name: jenkins

volumes:
  workspace:


