# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 2
  end

  config.vm.define "master.puppet", primary: true do |master|
    master.vm.hostname = "master.puppet"
    master.vm.network "private_network", ip: "192.168.56.11"
    master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
  end

  config.vm.define "slave1.puppet" do |slave1|
    slave1.vm.hostname = "slave1.puppet"
    slave1.vm.network "private_network", ip: "192.168.56.21"
    slave1.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "slave2.puppet" do |slave2|
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.network "private_network", ip: "192.168.56.22"
    slave2.vm.network "forwarded_port", guest: 80, host: 8081
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.groups   = {
      "master" => ["master.puppet"],
      "slave" => ["slave1.puppet", "slave2.puppet"],
      "slave:vars" => { "puppet_master": "192.168.56.11" }
    }
  end
end
