---
version: '3.3'
services:
 nexus:
   build:
     context: .
     dockerfile: DockerfileNexus
   image: nexustest
   ports: 
   - 81:8081
 jenkins:
   build:
     context: .
     dockerfile: DockerfileJenkins
   image: jenkinstest
   ports: 
   - 80:8080


